### ISSUE TITLE
No tengo permiso de escritura

### ISSUE THREAD

**Issue by danieldiezridner** [mmasias/24-25-PRG1-ExamenParcial#2]
Buenas, acabando la parte 2 del examen parcial, a la hora de hacer commit y subirlo, me pone que no tengo permiso de escritura sobre el repositorio en mi PC personal
Me gustaría poder arreglarlo mañana en clase si es posible

Un saludo
![imagen_2024-11-05_234856640](https://github.com/user-attachments/assets/8be0e865-e94c-4c8e-a719-3d6f8f6461bd)

**Comment by mmasias** [comment]
Ok Daniel. De todos modos, por lo que veo en la captura de pantalla:

   - Estás utilizando conceptos que no están permitidos (*arrays*)
   - Mantienes comentarios (que explícitamente hemos dicho que no han de
   utilizarse)
   - Los nombres de las constantes están incorrectas (*NUM_EDIFICIOS*
   deberia ser *NUMERO_DE_EDIFICIOS*)
      - además están declarados como variables estáticas fuera del método
      main, cosa que tampoco ha de utilizarse (aún)
   - Mantienes un *while (true)* cosa que es incorrecta
   - Persisten los magic numbers (70 deberia ser PROBABILIDAD_CASA_ABIERTA)

-
Manuel Masías
http://es.linkedin.com/in/mmasias

**Comment by mmasias** [comment]
También veo en la captura de pantalla que lo estás enviando mal: como está indicado en las[ instrucciones de la segunda parte del examen](https://github.com/mmasias/24-25-PRG1-ExamenParcial/blob/main/docs/parcialParte2.md), el repo de entrega es [este](https://classroom.github.com/assignment-invitations/1d1d76a5689a385e6f8f1bb3c9725f3a)

**Comment by danieldiezridner** [comment]
> este

Es que no lo he subido porque a la hora de hacer un Commit, siquiera a la hora de guardarlo me da el error de permiso de la escritura
